### ISSUE TITLE
Trigger PyPI releases only on tags that follow a v1.2.3 scheme

### ISSUE THREAD

**Issue by michaelosthege** [blsqr/paramspace#1]
Like this:

```
  only:
    # only run on refs on master that are named like v1.2 or v1.2.3
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
```

**Comment by blsqr** [comment]
Thanks for the suggestion! :) Such a safety measure makes a lot of sense. 👍 

Some remarks, though:
* I think one can assume version numbers to always include the patch release number (even if 0 is implied)
* Pre-release versions should be supported
* With GitLab 13.0, the `only`/`except` syntax [will be deprecated](https://about.gitlab.com/releases/2020/04/22/gitlab-12-10-released/#gitlab-ci/cd-pipeline-configuration-templates-are-transitioning-to-`rules`-instead-of-`only/except`); to be future-proof, moving to `rules` might make sense here
* The thing to mess up with the tag is imo not the _git_ tag itself, but that it triggers a PyPI push with an unintended version number, which is then blocked forever. To be totally on the safe side, one would additionally need to check that the Python version matches that of the git tag prior to pushing to PyPI.

A bash-compliant regex would be
```
^v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)([[:lower:]]\d+)?
```

If the last point is to be addressed, some additional logic inside the CI job would be required.

**Comment by blsqr** [comment]
FYI: I opened an issue over at the development repository, https://ts-gitlab.iup.uni-heidelberg.de/yunus/paramspace/-/issues/38.

**Comment by michaelosthege** [comment]
The pattern also matches `v1.2`.

I'd be interested in both the version with `rules`, as well as an additional line checking the match between the library version (maybe via the Wheel-file?) and the tag.

It took me several days and something like 13 pipeline runs on a test repository to get the Regex right though.. Let me know if you figure it out^

**Comment by blsqr** [comment]
> The pattern also matches v1.2.

Urgh, must be some GitLab regex parsing speciality then. The patch release and the preceding period is not marked as optional in the regex. Also, both in regex101 (see https://regex101.com/r/AsCCJo/4) and when evaluated in bash, the pattern matches only `v1.2.3` and pre-release versions...

```bash
$ export VERSION_PATTERN="v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)([[:lower:]]\d+)?"
$ if [[ "v1.2.3" =~ ${VERSION_PATTERN} ]]; then echo "true"; else echo "false"; fi
true
$ if [[ "v1.2" =~ ${VERSION_PATTERN} ]]; then echo "true"; else echo "false"; fi
false
```

> additional line checking the match between the library version (maybe via the Wheel-file?) and the tag.

One could parse `*.egg-info/PKG-INFO`, which is what PyPI uses, afaik; then use grep to perform the match:

```bash
$ export VERSION_NUMBER=${CI_COMMIT_TAG:1}  # get 1.2.3 from v1.2.3
$ cat my_package.egg-info/PKG-INFO | grep "^Version:\s+${VERSION_NUMBER}$"
$ ... # check exit code, continue accordingly
```

Alternatively, `pip show my_package` shows the same information.

>  `rules`

According to the docs, it looks like [`rules:if`](https://docs.gitlab.com/ee/ci/yaml/#rulesif) accepts the bash-compliant regex, right? 🤔 

I'll let you know when I implement this; but it's quite low on the priority list, currently.

**Comment by michaelosthege** [comment]
> The pattern also matches v1.2.
> 
> Urgh, must be some GitLab regex parsing speciality then. The patch release and the preceding period is not marked as optional in the regex. Also, both in regex101 (see https://regex101.com/r/AsCCJo/3) and when evaluated in bash, the pattern matches only v1.2.3 and pre-release versions...
> $ export VERSION_PATTERN="v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)([[:lower:]]\d+)?"
> $ if [[ "v1.2.3" =~ ${VERSION_PATTERN} ]]; then echo "true"; else echo "false"; fi
> true
> $ if [[ "v1.2" =~ ${VERSION_PATTERN} ]]; then echo "true"; else echo "false"; fi
> false
> 
> additional line checking the match between the library version (maybe via the Wheel-file?) and the tag.
> 
> One could parse *.egg-info/PKG-INFO, which is what PyPI uses, afaik; then use grep to perform the match:
> $ export VERSION_NUMBER=${CI_COMMIT_TAG:1}  # get 1.2.3 from v1.2.3
> $ cat my_package.egg-info/PKG-INFO | grep "^Version:\s+${VERSION_NUMBER}$"
> $ ... # check exit code, continue accordingly
> Alternatively, pip show my_package shows the same information.
> 
> rules
> 
> According to the docs, it looks like rules:if accepts the bash-compliant regex, right? 🤔
> I'll let you know when I implement this; but it's quite low on the priority list, currently.

Oh right - it matches `v1.2.` but not `v1.2`
I never actually used it without a patch version number. Sorry about that

**Comment by blsqr** [comment]
Oups! I thought you were referring to `^v([[:digit:]]+)\.([[:digit:]]+)\.([[:digit:]]+)([[:lower:]]\d+)?`, but you were actually referring to `/^v(\d+\.)?(\d+\.)?(\*|\d+)$/`, right? Sorry about that, too!

**Comment by blsqr** [comment]
Alright, this was resolved with [MR !36 over in the development repo](https://ts-gitlab.iup.uni-heidelberg.de/yunus/paramspace/-/merge_requests/36). 😊 

If you are interested, have a look at [the updated `.gitlab-ci.yml`](https://ts-gitlab.iup.uni-heidelberg.de/yunus/paramspace/-/blob/master/.gitlab-ci.yml#L138) for details.

**Comment by michaelosthege** [comment]
Very nice implementation! Thank you for sharing :)
